repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/mtkennerly/pre-commit-hooks
    rev: v0.4.0
    hooks:
      - id: poetry-mypy
      - id: poetry-ruff-check
      - id: poetry-ruff-format
